[package]
name = "color-coding"
version = "0.1.0"
authors = ["lcagustini <torresmon235@gmail.com>"]

[dependencies]
unicode-segmentation = "1.2.0"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
default-features = false
features = ["ttf","image"]
